louvre_booking_homepage:
    path:     /
    defaults: { _controller: LouvreBookingBundle:Default:index }

louvre_booking_booking:
    path:     /booking
    defaults: { _controller: LouvreBookingBundle:Booking:booking }

louvre_booking_test:
    path:     /test/{id}
    defaults: { _controller: LouvreBookingBundle:Booking:test }

louvre_booking_view:
    path:     /order/{id}
    defaults: { _controller: LouvreBookingBundle:Order:view }

louvre_booking_checkout:
    path:     /checkout
    defaults: { _controller: LouvreBookingBundle:Order:checkout }

louvre_booking_checked:
    path:     /checked/{code}
    defaults: { _controller: LouvreBookingBundle:Order:checked }

louvre_booking_mail:
    path:     /mail/{code}
    defaults: { _controller: LouvreBookingBundle:Order:testmail }
