louvre_booking_homepage:
    path:     /
    defaults: { _controller: LouvreBookingBundle:Default:index }

louvre_booking_booking:
    path:     /booking
    defaults: { _controller: LouvreBookingBundle:Default:booking }

louvre_booking_order:
    path:     /order
    defaults: { _controller: LouvreBookingBundle:Order:prepare }

louvre_booking_checkout:
    path:     /checkout
    defaults: { _controller: LouvreBookingBundle:Order:checkout }