# ===================== Routes DefaultController ==================================
louvre_booking_homepage:
    path:     /
    defaults: { _controller: LouvreBookingBundle:Default:index }

louvre_booking_mentions:
    path:     /mentions
    defaults: { _controller: LouvreBookingBundle:Default:mentions }

louvre_booking_contact:
    path:     /contact
    defaults: { _controller: LouvreBookingBundle:Default:contact }

# ===================== Routes BookingController ==================================
louvre_booking_booking:
    path:     /booking
    defaults: { _controller: LouvreBookingBundle:Booking:booking }

louvre_booking_test:
    path:     /test/{id}
    defaults: { _controller: LouvreBookingBundle:Booking:test }

# ===================== Routes OrderController ==================================
louvre_booking_view:
    path:     /order/{id}
    defaults: { _controller: LouvreBookingBundle:Order:view }

louvre_booking_checkout:
    path:     /checkout
    defaults: { _controller: LouvreBookingBundle:Order:checkout }

louvre_booking_checked:
    path:     /checked/{code}
    defaults: { _controller: LouvreBookingBundle:Order:checked }

louvre_booking_mail:
    path:     /mail/{code}
    defaults: { _controller: LouvreBookingBundle:Order:testmail }

# ===================== Routes ApiController ==================================
louvre_booking_api:
    path:     /api/{date}
    defaults: { _controller: LouvreBookingBundle:Api:nbrePlace }

louvre_booking_exclu:
    path:     /api_exclu
    defaults: { _controller: LouvreBookingBundle:Api:datesNoDispo }
