services:
    Louvre_Booking.Traitements:
#        resources: '../../src/Louvre/BookingBundle/Services/*'
        class: Louvre\BookingBundle\Services\Traitements
        arguments:
            - %billet_max%
