<?php

namespace Louvre\BookingBundle\Repository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends \Doctrine\ORM\EntityRepository
{
    public function listePays()
    {
        return $this
            ->createQueryBuilder('p')
            ->select('p.nomFrFr')
            ->orderBy('p.nomFrFr', 'ASC')
            ;
    }
}
