<?php

namespace Louvre\BookingBundle\Repository;

use Louvre\BookingBundle\Entity\Reservation;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function placeJours($date)
    {
        $query = $this->createQueryBuilder('r')
            ->select('SUM(r.nbrePlaces)')
            ->where('r.dateVisite = :date')
            ->andWhere('r.valided = 1')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult()
        ;
        return $query;
    }

    public function datesNonDispo()
    {
        $query = $this->createQueryBuilder('r')
            ->select('r.dateVisite', 'SUM(r.nbrePlaces) as Places')
            ->where('r.valided = 1')
            ->groupBy('r.dateVisite')
            ->getQuery()
            ->getScalarResult()
        ;
        return $query;
    }
}
