<?php

namespace Louvre\BookingBundle\Repository;

/**
 * eservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function resaWithdetails($id)
    {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('d.details', 'detailResa')
            ->addSelect('detailResa')
            ->andWhere('r.id = :resa_id')
            ->setParameter('resa_id', $id)
            ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
