<?php

namespace Louvre\BookingBundle\Repository;


/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function placeJours($date)
    {
        $query = $this->createQueryBuilder('r')
            ->select('COUNT(r.nbrePlaces)')
            ->where('r.dateVisite = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult()
            ;
        return $query;

    }
}
